[pytest]
python_files = test_*.py tests/*.py *_test.py
testpaths = tests
# (اختياري) إضافة خيارات أخرى هنا حسب الحاجة، مثل:
# addopts = --verbose
# markers =
#   smoke: subset of tests to run on each commit
#   regression: all tests for regression testing
